config/routes.rb
TravellerMap::Application.routes.draw do

  devise_for :users
  root :to => "subsectors#index"
  get "systems/:id/render_popup" => "systems#render_popup"
  resources :subsectors do
    resources :systems do
      get :render_popup
    end
  end

  resources :brokers

end

app/models/subsector.rb
class Subsector < ActiveRecord::Base
  belongs_to :user
  has_many :systems

  def gmed_by?(user)
    user == self.user
  end
end

app/controllers/subsectors_controller.rb
class SubsectorsController < ApplicationController
  def index
    @subsectors = Subsector.all
  end

  def show
    @subsector = Subsector.find params[:id]
    @systems = @subsector.systems.order(:row, :col).group_by(&:row)
  end
end

app/helpers/subsectors_helper.rb
module SubsectorsHelper
end

app/views/subsectors/index.html.haml
.content
  %h1 Subsector list
  - @subsectors.each do |subsector|
    = link_to subsector.name, subsector_path(subsector)

app/views/subsectors/show.html.haml
.content
  -@systems.each do |idx,row|
    .hexrow
      - row.each do |system|
        .hex{:id => system.id, :class => system.name.present? ? "present" : ""}
          .centre
            .hexcontent
              - if %w(Amber Red Purple).include?(system.travel_code)
                %div{class: system.travel_code.downcase}
              - system.bases.each do |b|
                %div{class: b.name.downcase.gsub(/\s+/,'_')}
                  = b.symbol
              %span.coords
                #{system.col.to_s.rjust(2, "0")}#{system.row.to_s.rjust(2, "0")}
              - if system.name.present?
                %span.starport
                  = system.starport
              %span.planet
                - unless system.name.blank?
                  .circle
              %span.name
                = system.name
            .tophalf{:class => system.links.include?(1) ? "background" : ""}
            .bottomhalf{:class => system.links.include?(4) ? "background" : ""}


          .slantright
            .tophalf{:class => system.links.include?(2) ? "background" : ""}
            .bottomhalf{:class => system.links.include?(5) ? "background" : ""}
          .slantleft
            .tophalf{:class => system.links.include?(6) ? "background" : ""}
            .bottomhalf{:class => system.links.include?(3) ? "background" : ""}