config/routes.rb
TravellerMap::Application.routes.draw do

  devise_for :users
  root :to => "subsectors#index"
  get "systems/:id/render_popup" => "systems#render_popup"
  resources :subsectors do
    resources :systems do
      get :render_popup
    end
  end

  resources :brokers

end

app/models/broker.rb
class Broker < ActiveRecord::Base
  belongs_to :system
  has_many :broker_trade_goods

  def assign_items(systems)
    goods = TradeGood.available_in(system) + TradeGood.special_items(rand(6)+1)

    items = []
    goods.each do |item|
      qty = item.ton_multiplier * (rand(6)+1)

      if good = broker_trade_goods.detect{|g| g.trade_good == item}
        good.quantity += qty
      else
        self.broker_trade_goods << BrokerTradeGood.new(trade_good: item, quantity: qty)
      end
    end
  end

  def self.broker_items_for(system)
    goods = TradeGood.available_in(system) + TradeGood.special_items(rand(6)+1)

    items = []
    goods.each do |item|
      qty = item.ton_multiplier * (rand(6)+1)
      items << {:item => item, :quantity => qty}
    end
    items
  end

  def self.print_broker_for(system)
    puts "Broker for #{system.name}"
    puts "Goods available"
    ActiveRecord::Base.silence do
      broker_items_for(system).each do |good|
        puts "Item: #{good[:item].name}"
        puts "Quantity: #{good[:quantity]} tonnes"
        puts "Purchase mod: #{good[:item].purchase_price_mod(system)}"
        puts "Sale mod: #{good[:item].sale_price_mod(system)}"
        puts "Base price: #{good[:item].base_price}"
        puts "Examples: #{good[:item].examples}"
        puts " "
      end
    end
    0
  end

end

app/controllers/brokers_controller.rb
class BrokersController < ApplicationController

  layout false, except: :index

  before_filter :find_system, except: :index

  def index
    respond_to do |format|
      format.html
      format.js {
        @from = System.find(params[:from])
        @to = System.find(params[:to])
      }
    end
  end

  def new
    @broker = @system.generate_broker
    redirect_to broker_path(@broker, system_id: @system.id)
  end

  def show
    @broker = @system.brokers.find(params[:id])
  end

  def destroy
    @broker = @system.brokers.find(params[:id])
    @broker.destroy
    @system.reload
  end

  private

  def find_system
    @system = System.find(params[:system_id])
  end
end

app/helpers/brokers_helper.rb
module BrokersHelper
end

app/views/brokers/_trade.haml
%ul.planet
  %li
    .label Name:
    .data= @from.name
  %li
    .label Trade Codes:
    - @from.trade_codes.each do |code|
      - next if code.name=~/zone$/i
      .data
        = code.name
  %li
    .label Travel Code:
    - if @from.travel_code.present?
      .data{:class => @from.travel_code == "Amber" ? "yellow-status" : "red-status"}= @from.travel_code
    -else
      .data{:class => "green-status"} Green
  %li
    .label Restrictions:
    - @from.show_contraband.each do |contraband|
      .data= contraband

%ul.planet
  %li
    .label Name:
    .data= @to.name
  %li
    .label Trade Codes:
    - @to.trade_codes.each do |code|
      - next if code.name=~/zone$/i
      .data
        = code.name
  %li
    .label Travel Code:
    - if @to.travel_code.present?
      .data{:class => @to.travel_code == "Amber" ? "yellow-status" : "red-status"}= @to.travel_code
    -else
      .data{:class => "green-status"} Green
  %li
    .label Restrictions:
    - @to.show_contraband.each do |contraband|
      .data= contraband

%table
  %thead
    %tr
      %th.left Trade Good
      %th.left Examples
      %th Base Price
      %th Purchase Mod
      %th Sale Mod
      %th.quantity Quantity
      %th.quantity
        Roll
        = select_tag "kind", options_for_select(%w(purchase sell))
      %th.total Total
  - TradeGood.all.each do |g|
    - if g.d66 == 66
      %tr
        %td.left= g.name
        %td.left{colspan: 7}= g.examples
    - else
      %tr
        %td.left= g.name
        %td.left= g.examples
        %td.price
          = number_with_delimiter(g.base_price)
          cr
        %td= g.purchase_price_mod(@from)
        %td= g.sale_price_mod(@to)
        %td.quantity= text_field_tag "quantity", ''
        %td.quantity= text_field_tag "roll", ''
        %td.total &nbsp;
  %tfoot
    %tr
      %td{colspan: 7} Total:
      %td.total 0 cr

app/views/brokers/destroy.js.erb
$('#brokers #broker_<%= @broker.id %>').remove();

app/views/brokers/index.html.haml
#broker-content
  = form_tag brokers_path, remote: true, :method => :get do
    %label Specify trade route
    %ul.filters
      %li
        %label From
        = select_tag "from", options_from_collection_for_select(System.with_planets.order(:name), :id, :name)
      %li
        %label To
        = select_tag "to", options_from_collection_for_select(System.with_planets.order(:name), :id, :name)
      %li
        = submit_tag "submit"
    .clear
  #broker-list

app/views/brokers/index.js.erb
console.log("hello")
$('#broker-list').html("<%= escape_javascript(render partial: 'trade') %>")
console.log("here")

app/views/brokers/show.haml
.popup_content
  .two_column#broker
    %ul
      %li
        .label Name:
        .data>= @broker.name
        .data> &nbsp;
      %li
        .label System
        .data>= @broker.system.name
        .data> &nbsp;
    #toggles
      = link_to 'purchase', '#purchase', class: 'toggle active'
      \|
      = link_to 'sell', '#sell', class: 'toggle'
    %ul#purchase
      - @broker.broker_trade_goods.includes(:trade_good).each do |good|
        %li
          .label= good.trade_good.name
          .data> Quantity: #{good.quantity} tonnes
          .data> Purchase mod: #{good.trade_good.purchase_price_mod(@system)}
          .data> Base price: #{number_with_delimiter(good.trade_good.base_price)} cr
          .data> Sale mod: #{good.trade_good.sale_price_mod(@system)}
          .data.full> Examples: #{good.trade_good.examples}
    %ul#sell{style: 'display:none'}
      - TradeGood.all.each do |tg|
        %li
          .label= tg.name
          .data> Base price: #{number_with_delimiter(tg.base_price)} cr
          .data> Sale mod: #{tg.sale_price_mod(@system)}